/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN,
    CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    VERCEL_AUTOMATION_BYPASS_SECRET: process.env.VERCEL_AUTOMATION_BYPASS_SECRET,
    CLOUDFLARE_AUTH_EMAIL : process.env.CLOUDFLARE_AUTH_EMAIL,
    CLOUDFLARE_GLOBAL_API_KEY : process.env.CLOUDFLARE_GLOBAL_API_KEY,
    RESEND_API_KEY : process.env.RESEND_API_KEY,
    DEFAULT_SENDER_EMAIL : process.env.DEFAULT_SENDER_EMAIL,
    INBOXING_API_KEY : process.env.INBOXING_API_KEY,
  },
}

module.exports = nextConfig
 